--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/luca28pet/MultiServerCounter
branches:
- master
projects:
  MultiServerCounter:
    path: ""
    libs:
      - src: jasonwynn10/libpmquery/libpmquery
        version: ^0.1.0
...
